Handle missing lsb attributes
       ================================================================================
       Recipe Compile Error in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/rabbitmq/attributes/default.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `[]' for nil:NilClass