Remove -q from rabbitmq-plugins list
"-q" doesn't seems to be a valid argument: 
```
root@manu-ubuntu2:/var/log/rabbitmq# rabbitmq-plugins
Error: could not recognise command
Usage:
rabbitmq-plugins [-n <node>] <command> [<command options>]

Commands:
    list [-v] [-m] [-E] [-e] [<pattern>]
    enable [--offline] [--online] <plugin> ...
    disable [--offline] [--online] <plugin> ...
    set [--offline] [--online] <plugin> ...
```
This -q breaks the recipe mgmt_console and I guess any recipe the use this providers.