Add missing notifies for ohai[reload_packages] on Fedora/RHEL
Without this, it doesn't properly run ``installed_rabbitmq_version`` and causes
an error:

```
  * ohai[reload_packages] action nothing (skipped due to action :nothing)
Recipe: rabbitmq::management_ui
  * rabbitmq_plugin[rabbitmq_management] action enable

    ================================================================================
    Error executing action `enable` on resource 'rabbitmq_plugin[rabbitmq_management]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /tmp/kitchen/cache/cookbooks/rabbitmq/libraries/default.rb:79:in `installed_rabbitmq_version'
    /tmp/kitchen/cache/cookbooks/rabbitmq/providers/plugin.rb:26:in `plugin_enabled?'
    /tmp/kitchen/cache/cookbooks/rabbitmq/providers/plugin.rb:40:in `block in class_from_file'
```

Signed-off-by: Lance Albertson <lance@osuosl.org>